/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        
        String initialLabel = welcomeLabel.getText();
        CentralProvider provider = new CentralProvider();
        String newWelcome = "Welcome " + provider.staffFname + " " + provider.staffLname + ", " + initialLabel;
        welcomeLabel.setText(newWelcome.toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        inserIconButton = new javax.swing.JButton();
        reportsIconButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        logoutIconButton = new javax.swing.JButton();
        sellIconButton = new javax.swing.JButton();
        editIconButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        insertButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sellButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        reportsButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        staffButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DASHBOARD");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 110, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\dashboard_64px.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 200, 100));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\2772672.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 130));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 790, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DASHBOARD");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 110, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\2772672.jpg")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 120));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\icons8-customer-64.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 170, 140));

        inserIconButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\icons8-login-64.png")); // NOI18N
        inserIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserIconButtonActionPerformed(evt);
            }
        });
        jPanel2.add(inserIconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 170, 140));

        reportsIconButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\icons8-business-report-96.png")); // NOI18N
        reportsIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsIconButtonActionPerformed(evt);
            }
        });
        jPanel2.add(reportsIconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 170, 140));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 790, -1));

        logoutIconButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\logout_64px.png")); // NOI18N
        logoutIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutIconButtonActionPerformed(evt);
            }
        });
        jPanel2.add(logoutIconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 170, 140));

        sellIconButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\icons8-mobile-80.png")); // NOI18N
        sellIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellIconButtonActionPerformed(evt);
            }
        });
        jPanel2.add(sellIconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 170, 140));

        editIconButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\edit_64px.png")); // NOI18N
        editIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editIconButtonActionPerformed(evt);
            }
        });
        jPanel2.add(editIconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 170, 140));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Insert Phone");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 30));

        insertButton.setBackground(new java.awt.Color(102, 51, 0));
        insertButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        insertButton.setForeground(new java.awt.Color(255, 255, 255));
        insertButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\2772672.jpg")); // NOI18N
        insertButton.setBorder(null);
        insertButton.setBorderPainted(false);
        insertButton.setContentAreaFilled(false);
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        jPanel2.add(insertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 133, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sell Phone");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, 30));

        sellButton.setBackground(new java.awt.Color(102, 51, 0));
        sellButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        sellButton.setForeground(new java.awt.Color(255, 255, 255));
        sellButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\2772672.jpg")); // NOI18N
        sellButton.setBorder(null);
        sellButton.setBorderPainted(false);
        sellButton.setContentAreaFilled(false);
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });
        jPanel2.add(sellButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 133, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reports");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, 30));

        reportsButton.setBackground(new java.awt.Color(102, 51, 0));
        reportsButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        reportsButton.setForeground(new java.awt.Color(255, 255, 255));
        reportsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\2772672.jpg")); // NOI18N
        reportsButton.setBorder(null);
        reportsButton.setBorderPainted(false);
        reportsButton.setContentAreaFilled(false);
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(reportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 133, 30));

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText(" TO GUARANTEE PHONE INVENTORY MANAGEMENT SYSTEM");
        jPanel2.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 670, 30));

        logoutLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLabel.setText("Logout");
        jPanel2.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, 30));

        logoutButton.setBackground(new java.awt.Color(102, 51, 0));
        logoutButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\2772672.jpg")); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 133, 30));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Staff Details");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, 30));

        staffButton.setBackground(new java.awt.Color(102, 51, 0));
        staffButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        staffButton.setForeground(new java.awt.Color(255, 255, 255));
        staffButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\2772672.jpg")); // NOI18N
        staffButton.setBorder(null);
        staffButton.setBorderPainted(false);
        staffButton.setContentAreaFilled(false);
        staffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButtonActionPerformed(evt);
            }
        });
        jPanel2.add(staffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 133, 30));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Edit");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, 30));

        editButton.setBackground(new java.awt.Color(102, 51, 0));
        editButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\2772672.jpg")); // NOI18N
        editButton.setBorder(null);
        editButton.setBorderPainted(false);
        editButton.setContentAreaFilled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel2.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 133, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertButtonActionPerformed

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellButtonActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void inserIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserIconButtonActionPerformed
        // TODO add your handling code here:
        new InsertWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_inserIconButtonActionPerformed

    private void reportsIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsIconButtonActionPerformed
        // TODO add your handling code here:
        new TabbedReports().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reportsIconButtonActionPerformed

    private void sellIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellIconButtonActionPerformed
        // TODO add your handling code here:
        new SellPhone().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sellIconButtonActionPerformed

    private void logoutIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutIconButtonActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutIconButtonActionPerformed

    private void staffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButtonActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_staffButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new StaffPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void editIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editIconButtonActionPerformed
        // TODO add your handling code here:
        new Edit().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_editIconButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JButton editIconButton;
    private javax.swing.JButton inserIconButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton logoutIconButton;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JButton reportsButton;
    private javax.swing.JButton reportsIconButton;
    private javax.swing.JButton sellButton;
    private javax.swing.JButton sellIconButton;
    private javax.swing.JButton staffButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
