/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class SellPhone extends javax.swing.JFrame {
    Connection con;

    /**
     * Creates new form SellPhone
     */
    
    ArrayList<Integer> inputList = new  ArrayList<Integer>();
    public SellPhone() {
        initComponents();
        
        deletedLabel.setVisible(false);
        
        if(!(inputList == null)){
            inputList.clear();
        }
        
        
        totalField.setEditable(false);
        setBackground(new Color (0, 0, 0, 0));
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        sellTable.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sellIdField = new javax.swing.JTextField();
        sellCartButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        sellTable = new javax.swing.JTable();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        totalField = new javax.swing.JTextField();
        deletedLabel = new javax.swing.JLabel();
        sellButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\icons8-mobile-80.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 110, 80));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SELL PHONE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 110, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Random\\toppic\\2772672.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 120));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Phone ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 130, 40));

        sellIdField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        sellIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellIdFieldActionPerformed(evt);
            }
        });
        jPanel1.add(sellIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 160, 40));

        sellCartButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        sellCartButton.setText("Insert into Cart");
        sellCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellCartButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sellCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 720, 10));

        jScrollPane1.setBorder(null);

        sellTable.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        sellTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "BRAND", "COLOR", "PRICE (#)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sellTable.setOpaque(false);
        sellTable.setShowHorizontalLines(false);
        sellTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(sellTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 660, 230));

        cancelButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cancelButton.setText("BACK");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 100, 30));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Grand Total");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 130, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 720, 10));

        totalField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        totalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalField.setText("0");
        totalField.setBorder(null);
        jPanel1.add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 120, 30));

        deletedLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        deletedLabel.setForeground(new java.awt.Color(255, 102, 102));
        deletedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletedLabel.setText("6 phones for $100");
        jPanel1.add(deletedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 320, 30));

        sellButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        sellButton.setText("SELL");
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sellButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellIdFieldActionPerformed

    private void sellCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellCartButtonActionPerformed
        if(deletedLabel.isVisible()){
            deletedLabel.setVisible(false);
        }
        
        ResultSet rs = null;
        try {
            // TODO add your handling code here:
            String id = sellIdField.getText().trim();
            if(id.isEmpty()){
                JOptionPane.showMessageDialog(null, "No ID Selected", "WARNING", HEIGHT);
                return;
            }
            
            String con_String = "jdbc:mysql://127.0.0.1:3306/phoneshop";
            con = DriverManager.getConnection(con_String, "root", "" );
            
            String str = "SELECT * FROM `products_stock` WHERE id=?";
            PreparedStatement ps = con.prepareStatement(str);
            ps.setString(1, id);
            
            rs = ps.executeQuery();
            if(! rs.isBeforeFirst()){
                JOptionPane.showMessageDialog(null, id + "ID does not exist", "WARNING", HEIGHT);
            }
            
            boolean b = new CentralProvider().dbToJtable(rs, sellTable, totalField, inputList);
            
            if(b){
                JOptionPane.showMessageDialog(null, "ID "+ id+ " alraedy inserted", "WARNING", HEIGHT);
            }
            
        } 
        catch (SQLException ex) {
            System.out.println(ex.toString() + " Error occured when sellCart button was clicked");
        }
        
    }//GEN-LAST:event_sellCartButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        // TODO add your handling code here:
        if(inputList.size() <1){
            JOptionPane.showMessageDialog(null, "No Phones selected", "WARNING", HEIGHT);
            return;
        }
        
        int rowUpdated = new CentralProvider().productToSales(inputList);
        new CentralProvider().updateTableAfterDelete(rowUpdated, deletedLabel, sellTable, totalField);
        
    }//GEN-LAST:event_sellButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellPhone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel deletedLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton sellButton;
    private javax.swing.JButton sellCartButton;
    private javax.swing.JTextField sellIdField;
    private javax.swing.JTable sellTable;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
